// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: subnet/v1/diff.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DiffContent is what the user signs: hash(serialize(DiffContent)).
type DiffContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Txs           []*SubnetTx            `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty"`
	EscrowId      string                 `protobuf:"bytes,3,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	PostStateRoot []byte                 `protobuf:"bytes,4,opt,name=post_state_root,json=postStateRoot,proto3" json:"post_state_root,omitempty"` // state root AFTER applying this diff's txs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffContent) Reset() {
	*x = DiffContent{}
	mi := &file_subnet_v1_diff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffContent) ProtoMessage() {}

func (x *DiffContent) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_v1_diff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffContent.ProtoReflect.Descriptor instead.
func (*DiffContent) Descriptor() ([]byte, []int) {
	return file_subnet_v1_diff_proto_rawDescGZIP(), []int{0}
}

func (x *DiffContent) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *DiffContent) GetTxs() []*SubnetTx {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *DiffContent) GetEscrowId() string {
	if x != nil {
		return x.EscrowId
	}
	return ""
}

func (x *DiffContent) GetPostStateRoot() []byte {
	if x != nil {
		return x.PostStateRoot
	}
	return nil
}

// SubnetTx wraps all 8 tx types in a oneof for deterministic serialization.
type SubnetTx struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Tx:
	//
	//	*SubnetTx_StartInference
	//	*SubnetTx_ConfirmStart
	//	*SubnetTx_FinishInference
	//	*SubnetTx_TimeoutInference
	//	*SubnetTx_Validation
	//	*SubnetTx_ValidationVote
	//	*SubnetTx_RevealSeed
	//	*SubnetTx_FinalizeRound
	Tx            isSubnetTx_Tx `protobuf_oneof:"tx"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetTx) Reset() {
	*x = SubnetTx{}
	mi := &file_subnet_v1_diff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetTx) ProtoMessage() {}

func (x *SubnetTx) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_v1_diff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetTx.ProtoReflect.Descriptor instead.
func (*SubnetTx) Descriptor() ([]byte, []int) {
	return file_subnet_v1_diff_proto_rawDescGZIP(), []int{1}
}

func (x *SubnetTx) GetTx() isSubnetTx_Tx {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *SubnetTx) GetStartInference() *MsgStartInference {
	if x != nil {
		if x, ok := x.Tx.(*SubnetTx_StartInference); ok {
			return x.StartInference
		}
	}
	return nil
}

func (x *SubnetTx) GetConfirmStart() *MsgConfirmStart {
	if x != nil {
		if x, ok := x.Tx.(*SubnetTx_ConfirmStart); ok {
			return x.ConfirmStart
		}
	}
	return nil
}

func (x *SubnetTx) GetFinishInference() *MsgFinishInference {
	if x != nil {
		if x, ok := x.Tx.(*SubnetTx_FinishInference); ok {
			return x.FinishInference
		}
	}
	return nil
}

func (x *SubnetTx) GetTimeoutInference() *MsgTimeoutInference {
	if x != nil {
		if x, ok := x.Tx.(*SubnetTx_TimeoutInference); ok {
			return x.TimeoutInference
		}
	}
	return nil
}

func (x *SubnetTx) GetValidation() *MsgValidation {
	if x != nil {
		if x, ok := x.Tx.(*SubnetTx_Validation); ok {
			return x.Validation
		}
	}
	return nil
}

func (x *SubnetTx) GetValidationVote() *MsgValidationVote {
	if x != nil {
		if x, ok := x.Tx.(*SubnetTx_ValidationVote); ok {
			return x.ValidationVote
		}
	}
	return nil
}

func (x *SubnetTx) GetRevealSeed() *MsgRevealSeed {
	if x != nil {
		if x, ok := x.Tx.(*SubnetTx_RevealSeed); ok {
			return x.RevealSeed
		}
	}
	return nil
}

func (x *SubnetTx) GetFinalizeRound() *MsgFinalizeRound {
	if x != nil {
		if x, ok := x.Tx.(*SubnetTx_FinalizeRound); ok {
			return x.FinalizeRound
		}
	}
	return nil
}

type isSubnetTx_Tx interface {
	isSubnetTx_Tx()
}

type SubnetTx_StartInference struct {
	StartInference *MsgStartInference `protobuf:"bytes,1,opt,name=start_inference,json=startInference,proto3,oneof"`
}

type SubnetTx_ConfirmStart struct {
	ConfirmStart *MsgConfirmStart `protobuf:"bytes,2,opt,name=confirm_start,json=confirmStart,proto3,oneof"`
}

type SubnetTx_FinishInference struct {
	FinishInference *MsgFinishInference `protobuf:"bytes,3,opt,name=finish_inference,json=finishInference,proto3,oneof"`
}

type SubnetTx_TimeoutInference struct {
	TimeoutInference *MsgTimeoutInference `protobuf:"bytes,4,opt,name=timeout_inference,json=timeoutInference,proto3,oneof"`
}

type SubnetTx_Validation struct {
	Validation *MsgValidation `protobuf:"bytes,5,opt,name=validation,proto3,oneof"`
}

type SubnetTx_ValidationVote struct {
	ValidationVote *MsgValidationVote `protobuf:"bytes,6,opt,name=validation_vote,json=validationVote,proto3,oneof"`
}

type SubnetTx_RevealSeed struct {
	RevealSeed *MsgRevealSeed `protobuf:"bytes,7,opt,name=reveal_seed,json=revealSeed,proto3,oneof"`
}

type SubnetTx_FinalizeRound struct {
	FinalizeRound *MsgFinalizeRound `protobuf:"bytes,8,opt,name=finalize_round,json=finalizeRound,proto3,oneof"`
}

func (*SubnetTx_StartInference) isSubnetTx_Tx() {}

func (*SubnetTx_ConfirmStart) isSubnetTx_Tx() {}

func (*SubnetTx_FinishInference) isSubnetTx_Tx() {}

func (*SubnetTx_TimeoutInference) isSubnetTx_Tx() {}

func (*SubnetTx_Validation) isSubnetTx_Tx() {}

func (*SubnetTx_ValidationVote) isSubnetTx_Tx() {}

func (*SubnetTx_RevealSeed) isSubnetTx_Tx() {}

func (*SubnetTx_FinalizeRound) isSubnetTx_Tx() {}

// ExecutorReceiptContent is what the executor signs for MsgConfirmStart.
type ExecutorReceiptContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InferenceId   uint64                 `protobuf:"varint,1,opt,name=inference_id,json=inferenceId,proto3" json:"inference_id,omitempty"`
	PromptHash    []byte                 `protobuf:"bytes,2,opt,name=prompt_hash,json=promptHash,proto3" json:"prompt_hash,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	InputLength   uint64                 `protobuf:"varint,4,opt,name=input_length,json=inputLength,proto3" json:"input_length,omitempty"`
	MaxTokens     uint64                 `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EscrowId      string                 `protobuf:"bytes,7,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	ConfirmedAt   int64                  `protobuf:"varint,8,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorReceiptContent) Reset() {
	*x = ExecutorReceiptContent{}
	mi := &file_subnet_v1_diff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorReceiptContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorReceiptContent) ProtoMessage() {}

func (x *ExecutorReceiptContent) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_v1_diff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorReceiptContent.ProtoReflect.Descriptor instead.
func (*ExecutorReceiptContent) Descriptor() ([]byte, []int) {
	return file_subnet_v1_diff_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutorReceiptContent) GetInferenceId() uint64 {
	if x != nil {
		return x.InferenceId
	}
	return 0
}

func (x *ExecutorReceiptContent) GetPromptHash() []byte {
	if x != nil {
		return x.PromptHash
	}
	return nil
}

func (x *ExecutorReceiptContent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ExecutorReceiptContent) GetInputLength() uint64 {
	if x != nil {
		return x.InputLength
	}
	return 0
}

func (x *ExecutorReceiptContent) GetMaxTokens() uint64 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ExecutorReceiptContent) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ExecutorReceiptContent) GetEscrowId() string {
	if x != nil {
		return x.EscrowId
	}
	return ""
}

func (x *ExecutorReceiptContent) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

// TimeoutVoteContent is what a host signs for a TimeoutVote.
type TimeoutVoteContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EscrowId      string                 `protobuf:"bytes,1,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	InferenceId   uint64                 `protobuf:"varint,2,opt,name=inference_id,json=inferenceId,proto3" json:"inference_id,omitempty"`
	Reason        TimeoutReason          `protobuf:"varint,3,opt,name=reason,proto3,enum=subnet.v1.TimeoutReason" json:"reason,omitempty"`
	Accept        bool                   `protobuf:"varint,4,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutVoteContent) Reset() {
	*x = TimeoutVoteContent{}
	mi := &file_subnet_v1_diff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutVoteContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutVoteContent) ProtoMessage() {}

func (x *TimeoutVoteContent) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_v1_diff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutVoteContent.ProtoReflect.Descriptor instead.
func (*TimeoutVoteContent) Descriptor() ([]byte, []int) {
	return file_subnet_v1_diff_proto_rawDescGZIP(), []int{3}
}

func (x *TimeoutVoteContent) GetEscrowId() string {
	if x != nil {
		return x.EscrowId
	}
	return ""
}

func (x *TimeoutVoteContent) GetInferenceId() uint64 {
	if x != nil {
		return x.InferenceId
	}
	return 0
}

func (x *TimeoutVoteContent) GetReason() TimeoutReason {
	if x != nil {
		return x.Reason
	}
	return TimeoutReason_TIMEOUT_REASON_UNSPECIFIED
}

func (x *TimeoutVoteContent) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

// StateSignatureContent is what a host signs for state attestation.
type StateSignatureContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateRoot     []byte                 `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	EscrowId      string                 `protobuf:"bytes,2,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	Nonce         uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSignatureContent) Reset() {
	*x = StateSignatureContent{}
	mi := &file_subnet_v1_diff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSignatureContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSignatureContent) ProtoMessage() {}

func (x *StateSignatureContent) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_v1_diff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSignatureContent.ProtoReflect.Descriptor instead.
func (*StateSignatureContent) Descriptor() ([]byte, []int) {
	return file_subnet_v1_diff_proto_rawDescGZIP(), []int{4}
}

func (x *StateSignatureContent) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *StateSignatureContent) GetEscrowId() string {
	if x != nil {
		return x.EscrowId
	}
	return ""
}

func (x *StateSignatureContent) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_subnet_v1_diff_proto protoreflect.FileDescriptor

const file_subnet_v1_diff_proto_rawDesc = "" +
	"\n" +
	"\x14subnet/v1/diff.proto\x12\tsubnet.v1\x1a\x12subnet/v1/tx.proto\"\x8f\x01\n" +
	"\vDiffContent\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12%\n" +
	"\x03txs\x18\x02 \x03(\v2\x13.subnet.v1.SubnetTxR\x03txs\x12\x1b\n" +
	"\tescrow_id\x18\x03 \x01(\tR\bescrowId\x12&\n" +
	"\x0fpost_state_root\x18\x04 \x01(\fR\rpostStateRoot\"\xbf\x04\n" +
	"\bSubnetTx\x12G\n" +
	"\x0fstart_inference\x18\x01 \x01(\v2\x1c.subnet.v1.MsgStartInferenceH\x00R\x0estartInference\x12A\n" +
	"\rconfirm_start\x18\x02 \x01(\v2\x1a.subnet.v1.MsgConfirmStartH\x00R\fconfirmStart\x12J\n" +
	"\x10finish_inference\x18\x03 \x01(\v2\x1d.subnet.v1.MsgFinishInferenceH\x00R\x0ffinishInference\x12M\n" +
	"\x11timeout_inference\x18\x04 \x01(\v2\x1e.subnet.v1.MsgTimeoutInferenceH\x00R\x10timeoutInference\x12:\n" +
	"\n" +
	"validation\x18\x05 \x01(\v2\x18.subnet.v1.MsgValidationH\x00R\n" +
	"validation\x12G\n" +
	"\x0fvalidation_vote\x18\x06 \x01(\v2\x1c.subnet.v1.MsgValidationVoteH\x00R\x0evalidationVote\x12;\n" +
	"\vreveal_seed\x18\a \x01(\v2\x18.subnet.v1.MsgRevealSeedH\x00R\n" +
	"revealSeed\x12D\n" +
	"\x0efinalize_round\x18\b \x01(\v2\x1b.subnet.v1.MsgFinalizeRoundH\x00R\rfinalizeRoundB\x04\n" +
	"\x02tx\"\x93\x02\n" +
	"\x16ExecutorReceiptContent\x12!\n" +
	"\finference_id\x18\x01 \x01(\x04R\vinferenceId\x12\x1f\n" +
	"\vprompt_hash\x18\x02 \x01(\fR\n" +
	"promptHash\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12!\n" +
	"\finput_length\x18\x04 \x01(\x04R\vinputLength\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x04R\tmaxTokens\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12\x1b\n" +
	"\tescrow_id\x18\a \x01(\tR\bescrowId\x12!\n" +
	"\fconfirmed_at\x18\b \x01(\x03R\vconfirmedAt\"\x9e\x01\n" +
	"\x12TimeoutVoteContent\x12\x1b\n" +
	"\tescrow_id\x18\x01 \x01(\tR\bescrowId\x12!\n" +
	"\finference_id\x18\x02 \x01(\x04R\vinferenceId\x120\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x18.subnet.v1.TimeoutReasonR\x06reason\x12\x16\n" +
	"\x06accept\x18\x04 \x01(\bR\x06accept\"i\n" +
	"\x15StateSignatureContent\x12\x1d\n" +
	"\n" +
	"state_root\x18\x01 \x01(\fR\tstateRoot\x12\x1b\n" +
	"\tescrow_id\x18\x02 \x01(\tR\bescrowId\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonceB\x0eZ\fsubnet/typesb\x06proto3"

var (
	file_subnet_v1_diff_proto_rawDescOnce sync.Once
	file_subnet_v1_diff_proto_rawDescData []byte
)

func file_subnet_v1_diff_proto_rawDescGZIP() []byte {
	file_subnet_v1_diff_proto_rawDescOnce.Do(func() {
		file_subnet_v1_diff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subnet_v1_diff_proto_rawDesc), len(file_subnet_v1_diff_proto_rawDesc)))
	})
	return file_subnet_v1_diff_proto_rawDescData
}

var file_subnet_v1_diff_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_subnet_v1_diff_proto_goTypes = []any{
	(*DiffContent)(nil),            // 0: subnet.v1.DiffContent
	(*SubnetTx)(nil),               // 1: subnet.v1.SubnetTx
	(*ExecutorReceiptContent)(nil), // 2: subnet.v1.ExecutorReceiptContent
	(*TimeoutVoteContent)(nil),     // 3: subnet.v1.TimeoutVoteContent
	(*StateSignatureContent)(nil),  // 4: subnet.v1.StateSignatureContent
	(*MsgStartInference)(nil),      // 5: subnet.v1.MsgStartInference
	(*MsgConfirmStart)(nil),        // 6: subnet.v1.MsgConfirmStart
	(*MsgFinishInference)(nil),     // 7: subnet.v1.MsgFinishInference
	(*MsgTimeoutInference)(nil),    // 8: subnet.v1.MsgTimeoutInference
	(*MsgValidation)(nil),          // 9: subnet.v1.MsgValidation
	(*MsgValidationVote)(nil),      // 10: subnet.v1.MsgValidationVote
	(*MsgRevealSeed)(nil),          // 11: subnet.v1.MsgRevealSeed
	(*MsgFinalizeRound)(nil),       // 12: subnet.v1.MsgFinalizeRound
	(TimeoutReason)(0),             // 13: subnet.v1.TimeoutReason
}
var file_subnet_v1_diff_proto_depIdxs = []int32{
	1,  // 0: subnet.v1.DiffContent.txs:type_name -> subnet.v1.SubnetTx
	5,  // 1: subnet.v1.SubnetTx.start_inference:type_name -> subnet.v1.MsgStartInference
	6,  // 2: subnet.v1.SubnetTx.confirm_start:type_name -> subnet.v1.MsgConfirmStart
	7,  // 3: subnet.v1.SubnetTx.finish_inference:type_name -> subnet.v1.MsgFinishInference
	8,  // 4: subnet.v1.SubnetTx.timeout_inference:type_name -> subnet.v1.MsgTimeoutInference
	9,  // 5: subnet.v1.SubnetTx.validation:type_name -> subnet.v1.MsgValidation
	10, // 6: subnet.v1.SubnetTx.validation_vote:type_name -> subnet.v1.MsgValidationVote
	11, // 7: subnet.v1.SubnetTx.reveal_seed:type_name -> subnet.v1.MsgRevealSeed
	12, // 8: subnet.v1.SubnetTx.finalize_round:type_name -> subnet.v1.MsgFinalizeRound
	13, // 9: subnet.v1.TimeoutVoteContent.reason:type_name -> subnet.v1.TimeoutReason
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_subnet_v1_diff_proto_init() }
func file_subnet_v1_diff_proto_init() {
	if File_subnet_v1_diff_proto != nil {
		return
	}
	file_subnet_v1_tx_proto_init()
	file_subnet_v1_diff_proto_msgTypes[1].OneofWrappers = []any{
		(*SubnetTx_StartInference)(nil),
		(*SubnetTx_ConfirmStart)(nil),
		(*SubnetTx_FinishInference)(nil),
		(*SubnetTx_TimeoutInference)(nil),
		(*SubnetTx_Validation)(nil),
		(*SubnetTx_ValidationVote)(nil),
		(*SubnetTx_RevealSeed)(nil),
		(*SubnetTx_FinalizeRound)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subnet_v1_diff_proto_rawDesc), len(file_subnet_v1_diff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subnet_v1_diff_proto_goTypes,
		DependencyIndexes: file_subnet_v1_diff_proto_depIdxs,
		MessageInfos:      file_subnet_v1_diff_proto_msgTypes,
	}.Build()
	File_subnet_v1_diff_proto = out.File
	file_subnet_v1_diff_proto_goTypes = nil
	file_subnet_v1_diff_proto_depIdxs = nil
}
