// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/pruning_state.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PruningState struct {
	PocBatchesPrunedEpoch            int64 `protobuf:"varint,1,opt,name=poc_batches_pruned_epoch,json=pocBatchesPrunedEpoch,proto3" json:"poc_batches_pruned_epoch,omitempty"`
	PocValidationsPrunedEpoch        int64 `protobuf:"varint,2,opt,name=poc_validations_pruned_epoch,json=pocValidationsPrunedEpoch,proto3" json:"poc_validations_pruned_epoch,omitempty"`
	InferencePrunedEpoch             int64 `protobuf:"varint,3,opt,name=inference_pruned_epoch,json=inferencePrunedEpoch,proto3" json:"inference_pruned_epoch,omitempty"`
	EpochGroupValidationsPrunedEpoch int64 `protobuf:"varint,4,opt,name=epoch_group_validations_pruned_epoch,json=epochGroupValidationsPrunedEpoch,proto3" json:"epoch_group_validations_pruned_epoch,omitempty"`
	SubnetPrunedEpoch                int64 `protobuf:"varint,5,opt,name=subnet_pruned_epoch,json=subnetPrunedEpoch,proto3" json:"subnet_pruned_epoch,omitempty"`
}

func (m *PruningState) Reset()         { *m = PruningState{} }
func (m *PruningState) String() string { return proto.CompactTextString(m) }
func (*PruningState) ProtoMessage()    {}
func (*PruningState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3e942f788f930ee, []int{0}
}
func (m *PruningState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PruningState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PruningState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PruningState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PruningState.Merge(m, src)
}
func (m *PruningState) XXX_Size() int {
	return m.Size()
}
func (m *PruningState) XXX_DiscardUnknown() {
	xxx_messageInfo_PruningState.DiscardUnknown(m)
}

var xxx_messageInfo_PruningState proto.InternalMessageInfo

func (m *PruningState) GetPocBatchesPrunedEpoch() int64 {
	if m != nil {
		return m.PocBatchesPrunedEpoch
	}
	return 0
}

func (m *PruningState) GetPocValidationsPrunedEpoch() int64 {
	if m != nil {
		return m.PocValidationsPrunedEpoch
	}
	return 0
}

func (m *PruningState) GetInferencePrunedEpoch() int64 {
	if m != nil {
		return m.InferencePrunedEpoch
	}
	return 0
}

func (m *PruningState) GetEpochGroupValidationsPrunedEpoch() int64 {
	if m != nil {
		return m.EpochGroupValidationsPrunedEpoch
	}
	return 0
}

func (m *PruningState) GetSubnetPrunedEpoch() int64 {
	if m != nil {
		return m.SubnetPrunedEpoch
	}
	return 0
}

func init() {
	proto.RegisterType((*PruningState)(nil), "inference.inference.PruningState")
}

func init() {
	proto.RegisterFile("inference/inference/pruning_state.proto", fileDescriptor_f3e942f788f930ee)
}

var fileDescriptor_f3e942f788f930ee = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcf, 0xcc, 0x4b, 0x4b,
	0x2d, 0x4a, 0xcd, 0x4b, 0x4e, 0xd5, 0x47, 0xb0, 0x0a, 0x8a, 0x4a, 0xf3, 0x32, 0xf3, 0xd2, 0xe3,
	0x8b, 0x4b, 0x12, 0x4b, 0x52, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x84, 0xe1, 0xd2, 0x7a,
	0x70, 0x96, 0xd2, 0x3e, 0x26, 0x2e, 0x9e, 0x00, 0x88, 0xe2, 0x60, 0x90, 0x5a, 0x21, 0x73, 0x2e,
	0x89, 0x82, 0xfc, 0xe4, 0xf8, 0xa4, 0xc4, 0x92, 0xe4, 0x8c, 0xd4, 0xe2, 0x78, 0x90, 0x41, 0xa9,
	0x29, 0xf1, 0xa9, 0x05, 0xf9, 0xc9, 0x19, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0xa2, 0x05,
	0xf9, 0xc9, 0x4e, 0x10, 0xe9, 0x00, 0xb0, 0xac, 0x2b, 0x48, 0x52, 0xc8, 0x9e, 0x4b, 0x06, 0xa4,
	0xb1, 0x2c, 0x31, 0x27, 0x33, 0x25, 0xb1, 0x24, 0x33, 0x3f, 0x0f, 0x4d, 0x33, 0x13, 0x58, 0xb3,
	0x64, 0x41, 0x7e, 0x72, 0x18, 0x42, 0x09, 0xb2, 0x01, 0x26, 0x5c, 0x62, 0x70, 0x77, 0xa1, 0x6a,
	0x65, 0x06, 0x6b, 0x15, 0x81, 0xcb, 0x22, 0xeb, 0xf2, 0xe3, 0x52, 0x01, 0x2b, 0x8a, 0x4f, 0x2f,
	0xca, 0x2f, 0x2d, 0xc0, 0x6d, 0x3d, 0x0b, 0xd8, 0x0c, 0x05, 0x30, 0xc7, 0x1d, 0xa4, 0x14, 0x87,
	0x2b, 0xf4, 0xb8, 0x84, 0x8b, 0x4b, 0x93, 0xf2, 0x52, 0x4b, 0x50, 0xb5, 0xb3, 0x82, 0xb5, 0x0b,
	0x42, 0xa4, 0x90, 0xd4, 0x3b, 0xf9, 0x9f, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83,
	0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43,
	0x94, 0x69, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x41, 0x51, 0x7e,
	0x4a, 0x69, 0x72, 0x49, 0x71, 0x72, 0x26, 0x5a, 0x44, 0x55, 0x20, 0xb1, 0x4b, 0x2a, 0x0b, 0x52,
	0x8b, 0x93, 0xd8, 0xc0, 0xb1, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x10, 0x6e, 0x31, 0x58,
	0xd8, 0x01, 0x00, 0x00,
}

func (m *PruningState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PruningState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PruningState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SubnetPrunedEpoch != 0 {
		i = encodeVarintPruningState(dAtA, i, uint64(m.SubnetPrunedEpoch))
		i--
		dAtA[i] = 0x28
	}
	if m.EpochGroupValidationsPrunedEpoch != 0 {
		i = encodeVarintPruningState(dAtA, i, uint64(m.EpochGroupValidationsPrunedEpoch))
		i--
		dAtA[i] = 0x20
	}
	if m.InferencePrunedEpoch != 0 {
		i = encodeVarintPruningState(dAtA, i, uint64(m.InferencePrunedEpoch))
		i--
		dAtA[i] = 0x18
	}
	if m.PocValidationsPrunedEpoch != 0 {
		i = encodeVarintPruningState(dAtA, i, uint64(m.PocValidationsPrunedEpoch))
		i--
		dAtA[i] = 0x10
	}
	if m.PocBatchesPrunedEpoch != 0 {
		i = encodeVarintPruningState(dAtA, i, uint64(m.PocBatchesPrunedEpoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPruningState(dAtA []byte, offset int, v uint64) int {
	offset -= sovPruningState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PruningState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PocBatchesPrunedEpoch != 0 {
		n += 1 + sovPruningState(uint64(m.PocBatchesPrunedEpoch))
	}
	if m.PocValidationsPrunedEpoch != 0 {
		n += 1 + sovPruningState(uint64(m.PocValidationsPrunedEpoch))
	}
	if m.InferencePrunedEpoch != 0 {
		n += 1 + sovPruningState(uint64(m.InferencePrunedEpoch))
	}
	if m.EpochGroupValidationsPrunedEpoch != 0 {
		n += 1 + sovPruningState(uint64(m.EpochGroupValidationsPrunedEpoch))
	}
	if m.SubnetPrunedEpoch != 0 {
		n += 1 + sovPruningState(uint64(m.SubnetPrunedEpoch))
	}
	return n
}

func sovPruningState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPruningState(x uint64) (n int) {
	return sovPruningState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PruningState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPruningState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PruningState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PruningState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocBatchesPrunedEpoch", wireType)
			}
			m.PocBatchesPrunedEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruningState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocBatchesPrunedEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocValidationsPrunedEpoch", wireType)
			}
			m.PocValidationsPrunedEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruningState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocValidationsPrunedEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InferencePrunedEpoch", wireType)
			}
			m.InferencePrunedEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruningState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InferencePrunedEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochGroupValidationsPrunedEpoch", wireType)
			}
			m.EpochGroupValidationsPrunedEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruningState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochGroupValidationsPrunedEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubnetPrunedEpoch", wireType)
			}
			m.SubnetPrunedEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPruningState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubnetPrunedEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPruningState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPruningState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPruningState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPruningState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPruningState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPruningState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPruningState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPruningState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPruningState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPruningState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPruningState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPruningState = fmt.Errorf("proto: unexpected end of group")
)
