// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/subnet_settlement.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SubnetHostStatsProto struct {
	SlotId               uint32 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Missed               uint32 `protobuf:"varint,2,opt,name=missed,proto3" json:"missed,omitempty"`
	Invalid              uint32 `protobuf:"varint,3,opt,name=invalid,proto3" json:"invalid,omitempty"`
	Cost                 uint64 `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	RequiredValidations  uint32 `protobuf:"varint,5,opt,name=required_validations,json=requiredValidations,proto3" json:"required_validations,omitempty"`
	CompletedValidations uint32 `protobuf:"varint,6,opt,name=completed_validations,json=completedValidations,proto3" json:"completed_validations,omitempty"`
}

func (m *SubnetHostStatsProto) Reset()         { *m = SubnetHostStatsProto{} }
func (m *SubnetHostStatsProto) String() string { return proto.CompactTextString(m) }
func (*SubnetHostStatsProto) ProtoMessage()    {}
func (*SubnetHostStatsProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9fbc26d3059ce2, []int{0}
}
func (m *SubnetHostStatsProto) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubnetHostStatsProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubnetHostStatsProto.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubnetHostStatsProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetHostStatsProto.Merge(m, src)
}
func (m *SubnetHostStatsProto) XXX_Size() int {
	return m.Size()
}
func (m *SubnetHostStatsProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetHostStatsProto.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetHostStatsProto proto.InternalMessageInfo

func (m *SubnetHostStatsProto) GetSlotId() uint32 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *SubnetHostStatsProto) GetMissed() uint32 {
	if m != nil {
		return m.Missed
	}
	return 0
}

func (m *SubnetHostStatsProto) GetInvalid() uint32 {
	if m != nil {
		return m.Invalid
	}
	return 0
}

func (m *SubnetHostStatsProto) GetCost() uint64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *SubnetHostStatsProto) GetRequiredValidations() uint32 {
	if m != nil {
		return m.RequiredValidations
	}
	return 0
}

func (m *SubnetHostStatsProto) GetCompletedValidations() uint32 {
	if m != nil {
		return m.CompletedValidations
	}
	return 0
}

type SubnetHostStatsMapProto struct {
	Entries []*SubnetHostStatsProto `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (m *SubnetHostStatsMapProto) Reset()         { *m = SubnetHostStatsMapProto{} }
func (m *SubnetHostStatsMapProto) String() string { return proto.CompactTextString(m) }
func (*SubnetHostStatsMapProto) ProtoMessage()    {}
func (*SubnetHostStatsMapProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9fbc26d3059ce2, []int{1}
}
func (m *SubnetHostStatsMapProto) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubnetHostStatsMapProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubnetHostStatsMapProto.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubnetHostStatsMapProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetHostStatsMapProto.Merge(m, src)
}
func (m *SubnetHostStatsMapProto) XXX_Size() int {
	return m.Size()
}
func (m *SubnetHostStatsMapProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetHostStatsMapProto.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetHostStatsMapProto proto.InternalMessageInfo

func (m *SubnetHostStatsMapProto) GetEntries() []*SubnetHostStatsProto {
	if m != nil {
		return m.Entries
	}
	return nil
}

type SubnetStateSignatureContent struct {
	StateRoot []byte `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	EscrowId  string `protobuf:"bytes,2,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	Nonce     uint64 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *SubnetStateSignatureContent) Reset()         { *m = SubnetStateSignatureContent{} }
func (m *SubnetStateSignatureContent) String() string { return proto.CompactTextString(m) }
func (*SubnetStateSignatureContent) ProtoMessage()    {}
func (*SubnetStateSignatureContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9fbc26d3059ce2, []int{2}
}
func (m *SubnetStateSignatureContent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubnetStateSignatureContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubnetStateSignatureContent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubnetStateSignatureContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetStateSignatureContent.Merge(m, src)
}
func (m *SubnetStateSignatureContent) XXX_Size() int {
	return m.Size()
}
func (m *SubnetStateSignatureContent) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetStateSignatureContent.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetStateSignatureContent proto.InternalMessageInfo

func (m *SubnetStateSignatureContent) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *SubnetStateSignatureContent) GetEscrowId() string {
	if m != nil {
		return m.EscrowId
	}
	return ""
}

func (m *SubnetStateSignatureContent) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func init() {
	proto.RegisterType((*SubnetHostStatsProto)(nil), "inference.inference.SubnetHostStatsProto")
	proto.RegisterType((*SubnetHostStatsMapProto)(nil), "inference.inference.SubnetHostStatsMapProto")
	proto.RegisterType((*SubnetStateSignatureContent)(nil), "inference.inference.SubnetStateSignatureContent")
}

func init() {
	proto.RegisterFile("inference/inference/subnet_settlement.proto", fileDescriptor_2d9fbc26d3059ce2)
}

var fileDescriptor_2d9fbc26d3059ce2 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcb, 0xca, 0xd3, 0x40,
	0x14, 0xee, 0xd8, 0x34, 0xb5, 0xa3, 0x6e, 0xa6, 0xd1, 0x06, 0x8a, 0xa1, 0x74, 0x55, 0x11, 0x52,
	0xb4, 0xf8, 0x02, 0x76, 0x63, 0x17, 0xa2, 0xa4, 0xe0, 0xc2, 0x85, 0x21, 0x9d, 0x1c, 0xeb, 0x40,
	0x32, 0x27, 0xce, 0x9c, 0x78, 0x79, 0x0b, 0x1f, 0xcb, 0x65, 0x97, 0x6e, 0x84, 0x9f, 0xf6, 0x45,
	0x7e, 0x32, 0xa1, 0x17, 0x4a, 0x77, 0xdf, 0x75, 0x71, 0x3e, 0x0e, 0x7f, 0xa9, 0xf4, 0x57, 0x30,
	0xa0, 0x25, 0xcc, 0xcf, 0xc8, 0xd6, 0x1b, 0x0d, 0x94, 0x5a, 0x20, 0x2a, 0xa0, 0x04, 0x4d, 0x71,
	0x65, 0x90, 0x50, 0x0c, 0x4f, 0x91, 0xf8, 0x84, 0xa6, 0xff, 0x19, 0x0f, 0xd6, 0xae, 0xf0, 0x0e,
	0x2d, 0xad, 0x29, 0x23, 0xfb, 0xd1, 0xa5, 0x47, 0xbc, 0x6f, 0x0b, 0xa4, 0x54, 0xe5, 0x21, 0x9b,
	0xb0, 0xd9, 0x93, 0xc4, 0x6f, 0xe8, 0x2a, 0x17, 0xcf, 0xb8, 0x5f, 0x2a, 0x6b, 0x21, 0x0f, 0x1f,
	0xb4, 0x7a, 0xcb, 0x44, 0xc8, 0xfb, 0x4a, 0xff, 0xc8, 0x0a, 0x95, 0x87, 0x5d, 0x67, 0x1c, 0xa9,
	0x10, 0xdc, 0x93, 0x68, 0x29, 0xf4, 0x26, 0x6c, 0xe6, 0x25, 0x0e, 0x8b, 0x57, 0x3c, 0x30, 0xf0,
	0xbd, 0x56, 0x06, 0xf2, 0xd4, 0xa5, 0x32, 0x52, 0xa8, 0x6d, 0xd8, 0x73, 0xd5, 0xe1, 0xd1, 0xfb,
	0x74, 0xb6, 0xc4, 0x82, 0x3f, 0x95, 0x58, 0x56, 0x05, 0xd0, 0x55, 0xc7, 0x77, 0x9d, 0xe0, 0x64,
	0x5e, 0x94, 0xa6, 0x5f, 0xf8, 0xe8, 0xea, 0xbc, 0xf7, 0x59, 0xd5, 0x5e, 0xb8, 0xe4, 0x7d, 0xd0,
	0x64, 0x14, 0xd8, 0x90, 0x4d, 0xba, 0xb3, 0x47, 0xaf, 0x5f, 0xc4, 0x37, 0x16, 0x8a, 0x6f, 0xad,
	0x93, 0x1c, 0x9b, 0x53, 0xe4, 0xe3, 0x36, 0xd0, 0x98, 0xb0, 0x56, 0x5b, 0x9d, 0x51, 0x6d, 0x60,
	0x89, 0x9a, 0x40, 0x93, 0x78, 0xce, 0xb9, 0x6d, 0x8c, 0xd4, 0x20, 0x92, 0x1b, 0xf2, 0x71, 0x32,
	0x70, 0x4a, 0x82, 0x48, 0x62, 0xcc, 0x07, 0x60, 0xa5, 0xc1, 0x9f, 0xcd, 0xcc, 0xcd, 0x9c, 0x83,
	0xe4, 0x61, 0x2b, 0xac, 0x72, 0x11, 0xf0, 0x9e, 0x46, 0x2d, 0xc1, 0xcd, 0xe9, 0x25, 0x2d, 0x79,
	0xfb, 0xe1, 0xef, 0x3e, 0x62, 0xbb, 0x7d, 0xc4, 0xee, 0xf6, 0x11, 0xfb, 0x73, 0x88, 0x3a, 0xbb,
	0x43, 0xd4, 0xf9, 0x77, 0x88, 0x3a, 0x9f, 0xdf, 0x6c, 0x15, 0x7d, 0xab, 0x37, 0xb1, 0xc4, 0x72,
	0x5e, 0x19, 0xcc, 0x6b, 0x49, 0x56, 0xaa, 0xab, 0xe7, 0xf8, 0x75, 0x81, 0xe9, 0x77, 0x05, 0x76,
	0xe3, 0xbb, 0xef, 0x58, 0xdc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x74, 0x1c, 0x2f, 0x4c, 0x02,
	0x00, 0x00,
}

func (m *SubnetHostStatsProto) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubnetHostStatsProto) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubnetHostStatsProto) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CompletedValidations != 0 {
		i = encodeVarintSubnetSettlement(dAtA, i, uint64(m.CompletedValidations))
		i--
		dAtA[i] = 0x30
	}
	if m.RequiredValidations != 0 {
		i = encodeVarintSubnetSettlement(dAtA, i, uint64(m.RequiredValidations))
		i--
		dAtA[i] = 0x28
	}
	if m.Cost != 0 {
		i = encodeVarintSubnetSettlement(dAtA, i, uint64(m.Cost))
		i--
		dAtA[i] = 0x20
	}
	if m.Invalid != 0 {
		i = encodeVarintSubnetSettlement(dAtA, i, uint64(m.Invalid))
		i--
		dAtA[i] = 0x18
	}
	if m.Missed != 0 {
		i = encodeVarintSubnetSettlement(dAtA, i, uint64(m.Missed))
		i--
		dAtA[i] = 0x10
	}
	if m.SlotId != 0 {
		i = encodeVarintSubnetSettlement(dAtA, i, uint64(m.SlotId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SubnetHostStatsMapProto) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubnetHostStatsMapProto) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubnetHostStatsMapProto) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSubnetSettlement(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *SubnetStateSignatureContent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubnetStateSignatureContent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubnetStateSignatureContent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nonce != 0 {
		i = encodeVarintSubnetSettlement(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x18
	}
	if len(m.EscrowId) > 0 {
		i -= len(m.EscrowId)
		copy(dAtA[i:], m.EscrowId)
		i = encodeVarintSubnetSettlement(dAtA, i, uint64(len(m.EscrowId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.StateRoot) > 0 {
		i -= len(m.StateRoot)
		copy(dAtA[i:], m.StateRoot)
		i = encodeVarintSubnetSettlement(dAtA, i, uint64(len(m.StateRoot)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSubnetSettlement(dAtA []byte, offset int, v uint64) int {
	offset -= sovSubnetSettlement(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SubnetHostStatsProto) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlotId != 0 {
		n += 1 + sovSubnetSettlement(uint64(m.SlotId))
	}
	if m.Missed != 0 {
		n += 1 + sovSubnetSettlement(uint64(m.Missed))
	}
	if m.Invalid != 0 {
		n += 1 + sovSubnetSettlement(uint64(m.Invalid))
	}
	if m.Cost != 0 {
		n += 1 + sovSubnetSettlement(uint64(m.Cost))
	}
	if m.RequiredValidations != 0 {
		n += 1 + sovSubnetSettlement(uint64(m.RequiredValidations))
	}
	if m.CompletedValidations != 0 {
		n += 1 + sovSubnetSettlement(uint64(m.CompletedValidations))
	}
	return n
}

func (m *SubnetHostStatsMapProto) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovSubnetSettlement(uint64(l))
		}
	}
	return n
}

func (m *SubnetStateSignatureContent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StateRoot)
	if l > 0 {
		n += 1 + l + sovSubnetSettlement(uint64(l))
	}
	l = len(m.EscrowId)
	if l > 0 {
		n += 1 + l + sovSubnetSettlement(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovSubnetSettlement(uint64(m.Nonce))
	}
	return n
}

func sovSubnetSettlement(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSubnetSettlement(x uint64) (n int) {
	return sovSubnetSettlement(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SubnetHostStatsProto) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSubnetSettlement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubnetHostStatsProto: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubnetHostStatsProto: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotId", wireType)
			}
			m.SlotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Missed", wireType)
			}
			m.Missed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Missed |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invalid", wireType)
			}
			m.Invalid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Invalid |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cost", wireType)
			}
			m.Cost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredValidations", wireType)
			}
			m.RequiredValidations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequiredValidations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedValidations", wireType)
			}
			m.CompletedValidations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedValidations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSubnetSettlement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSubnetSettlement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubnetHostStatsMapProto) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSubnetSettlement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubnetHostStatsMapProto: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubnetHostStatsMapProto: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSubnetSettlement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSubnetSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, &SubnetHostStatsProto{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSubnetSettlement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSubnetSettlement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubnetStateSignatureContent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSubnetSettlement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubnetStateSignatureContent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubnetStateSignatureContent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSubnetSettlement
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSubnetSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRoot = append(m.StateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StateRoot == nil {
				m.StateRoot = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSubnetSettlement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSubnetSettlement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EscrowId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSubnetSettlement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSubnetSettlement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSubnetSettlement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSubnetSettlement(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSubnetSettlement
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSubnetSettlement
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSubnetSettlement
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSubnetSettlement
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSubnetSettlement
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSubnetSettlement
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSubnetSettlement        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSubnetSettlement          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSubnetSettlement = fmt.Errorf("proto: unexpected end of group")
)
